### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Edwin38H#2]
[Gestion de proyextos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Edwin38H/files/9435696/Gestion.de.proyextos.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18
Bien hecho y revisado
